### ISSUE TITLE
Error: no applicable method for 'predict' applied to an object of class "c('cforest', 'constparties', 'parties')"

### ISSUE THREAD

**Issue by vlntnzl** [EricPetermann/radon_exposure_germany#9]
The [model website ](https://model.radonmap.info/) is now online.

Of course, not everything works smoothly here either.

The display and selection of the location works without any problems.

However, when calculating (predict) in step 3, a resource error occurs:

`no applicable method for 'predict' applied to an object of class "c('cforest', 'constparties', 'parties')"
`

In addition, the browser displays the following message:

```
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: https://model.radonmap.info/jquery-3.6.0/jquery.min.js
Source-Map-Adresse: jquery.min.js.map
```

[Firefox help](https://firefox-source-docs.mozilla.org/devtools-user/debugger/source_map_errors/#source-map-missing-or-inaccessible)

```
The source map resource can be missing or inaccessible.
The fix here is to make sure the file is being served and is accessible to the browser.
```

It is quite possible that the two errors are connected and require further investigation.

However, if you have any ideas about the first error, please write something about it.

It is quite possible that the two errors are connected and require further investigation.

However, if you @EricPetermann have any ideas about the first error, please write something about it.

**Comment by EricPetermann** [comment]
The first error seems to be related to the model. Maybe when using the model created under the new environment we need to make clear that we want to use the predict function from the partykit package

Please try
`library(partykit)`
`pred <- partykit::predict(mod,newdata=newdata(),type="response",FUN=myQuantile)  #make prediction`

**Comment by EricPetermann** [comment]
I do not receive the second error message when using the app.

**Comment by vlntnzl** [comment]
> The first error seems to be related to the model. Maybe when using the model created under the new environment we need to make clear that we want to use the predict function from the partykit package
> 
> Please try `library(partykit)` `pred <- partykit::predict(mod,newdata=newdata(),type="response",FUN=myQuantile) #make prediction`

Installed partykit and used the partykit::predict command.

New error: `'predict' is not an exported object from 'namespace:partykit'`.

Possible solution [here](https://community.rstudio.com/t/problems-with-predict/140962/6):

 _Turns out, wrong input-format for stats::predict() leads to this missleading error message- because stats is 'guessing' to forecast an ets._

**Comment by vlntnzl** [comment]
Got the solution [here](https://stackoverflow.com/a/63219657).


```
I encountered this "Error: 'weekly' is not an exported object from 'namespace:ISLR'' when I was trying the following:

library(ISLR)

w <- ISLR::weekly

The problem is somehow fixed by changing it to:

w = ISLR::weekly

The = sign made all the difference here.
```

**Comment by vlntnzl** [comment]
Should be fixed - please have a look at the model website @EricPetermann !
